parameters:
  comments: ""
  recordid: ""
  projectid: ""
  queuedbyname: ""
  queuedbyemail: ""
  pipelinepowerautomate: ""
  components: []

stages:
- stage: PreBuild
  displayName: "Pre-Build Stage"
  isSkippable: false

  jobs:
  #get dataverse token and log
  - template: ../jobs/dataverse-token-job.yml
    parameters:
      comments: "${{ parameters.comments }}"
      recordid: "${{ parameters.recordid }}"      
      projectid: "${{ parameters.projectid }}"
      pipelinepowerautomate: "${{ parameters.pipelinepowerautomate }}"